# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rice_mill', '0002_auto_20170107_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag_types',
            name='bag_type',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='broker',
            name='broker_name',
            field=models.TextField(default='unknown', max_length=256),
        ),
        migrations.AlterField(
            model_name='rice_variety',
            name='rice_type',
            field=models.CharField(max_length=100),
        ),
    ]
